name: ci
on: [push, pull_request]
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - php_version: "8.3"
        env:
            PHP_VERSION: ${{ matrix.php_version }}
            DOCKER_USER_ID: "1001"
        steps:
            - name: clone
              uses: actions/checkout@v3
            - name: Setup DDEV
              uses: ddev/github-action-setup-ddev@v1
            - name: composer self-update
              run: ddev composer self-update
            - name: composer install
              run: ddev composer install
            - name: PHPCS
              run: ddev phpcs
            - name: PHPStan
              run: ddev phpstan
